theme: jekyll-theme-cayman
title: Data4Free

baseurl: /
exclude: ['README.md']
permalink: pretty

# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
  
<link href="{{site.baseurl}}/css/syntax.css" rel="stylesheet">
